"""
    api/pagination.py

    This file defines the following custom pagination class

    ## Classes
    * `PageCountPaginator`:  Inheriting the `PageNumberPaginator`, this paginator class has identical behavior.  
                             The only difference is the inclusion of the total count of pages generated by the
                             number of records and the number of records per page. 
"""
from rest_framework.pagination import PageNumberPagination
from rest_framework.response import Response


class PageCountPaginator(PageNumberPagination):
    """Implements all behaviors from `PageNumberPagination` class but results includet `page_count` value."""

    def get_paginated_response(self, data):
        return Response({
            'count': self.page.paginator.count,
            'page_count': self.page.paginator.num_pages,
            'results': data
        })
