# Generated by Django 3.1.5 on 2021-02-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210220_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedcopy',
            name='late_fee',
            field=models.FloatField(default=0.0, help_text='Late fee assessed (if any)', verbose_name='Late Fee'),
        ),
    ]
