# Generated by Django 3.1.5 on 2021-02-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20210221_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedcopy',
            name='late_fee',
            field=models.FloatField(default=0.0, help_text='Late fee assessed (if any)', null=True, verbose_name='Late Fee'),
        ),
    ]
