# Generated by Django 3.1.5 on 2021-03-22 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20210322_1002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['id'], 'verbose_name': 'Copy', 'verbose_name_plural': 'Copies'},
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='due_date',
        ),
    ]
