# Generated by Django 3.1.5 on 2021-03-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20210322_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedcopy',
            name='late_fee_paid',
            field=models.BooleanField(default=False, verbose_name='Late Fee Paid'),
        ),
    ]
